### ISSUE TITLE
Alterações

### ISSUE THREAD

**Issue by Renato66** [buildinginfraweb/site#1]
# Alterações

## Home

- [x] **Adicionar carrosel** *
- [x] Adicionar a versão em português do we do it, manter a versão em inglês
- [x] Remover as 3 imagens que estão sobrepondo a tela inicial
- [x] Remover o conteúdo da home e textos
- [x] Manter o formulário de contato

## Sobre nós

- [x] Subir os textos para página principal

## Nosso time

- [x] Subir os textos para página principal
- [ ] **Colocar as imagens do time na tela principal**

## Serviços

- [x] Subir os textos para página principal
- [x] Incluir botão call to action, para rolar a página para baixo
- [x] **Substituir imagens por imagens e texto**

## Contato

- [x] Subir o formulário de contato para página principal

## Parceiros

- [x] Incluir página parceiros no menu
- [x] **Incluir 4 parceiros**

## Etc

- [x] Trocar 'SOB DEMANDA' para  'Atendimento ao Cliente' e incluir link para sharepoint
- [x] Revisar textos das páginas
- [x] Trocar numero de whatsapp

edit: itens adicionais marcados com *

**Comment by Renato66** [comment]
A gravação ta numa qualidade de uma batata, mas é para dar a ideia de como fica:
![screen_recording (9)](https://user-images.githubusercontent.com/9284273/86314683-a4408300-bbfe-11ea-852f-27d3ae866f98.gif)
![screen_recording (8)](https://user-images.githubusercontent.com/9284273/86314649-91c64980-bbfe-11ea-9627-029b7a7c75de.gif)

**Comment by Renato66** [comment]
![image](https://user-images.githubusercontent.com/9284273/86557508-bab34b00-bf2c-11ea-99c8-c80882312707.png)
![image](https://user-images.githubusercontent.com/9284273/86557537-cbfc5780-bf2c-11ea-93fa-a9ff281b4cd2.png)

**Comment by persinando** [comment]
> A gravação ta numa qualidade de uma batata, mas é para dar a ideia de como fica:
> ![screen_recording (9)](https://user-images.githubusercontent.com/9284273/86314683-a4408300-bbfe-11ea-852f-27d3ae866f98.gif)
> ![screen_recording (8)](https://user-images.githubusercontent.com/9284273/86314649-91c64980-bbfe-11ea-9627-029b7a7c75de.gif)

Olá Renatinho. Gostei. Mas ainda estou sentindo que falta algo. Eu gostei sim de como ficou mais o que você acha ?

**Comment by persinando** [comment]
Relação aos contatos, gostei de como ficou, na forma de 2 colunas como havíamos conversado não ficou legal ?

**Comment by persinando** [comment]
Esse fosse algo assim o que você acha, ficaria melhor ?
![Home06072020](https://user-images.githubusercontent.com/58295294/86593220-3207cf80-bf6b-11ea-9a71-23791c434230.jpg)
